name: "co"

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    volumes:
      - ..:/rails
      - bundle:/usr/local/bundle
      - rails_cache:/rails/tmp/cache

    environment:
      RAILS_ENV: development
      DATABASE_ADAPTER: sqlite3
      DATABASE_STORAGE: /workspaces/db/development.sqlite3

    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0"

    ports:
      - "3000:3000"

volumes:
  bundle:
  rails_cache:
